// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :exec
insert into images (
    title, artist, dark, data
) values (
    ?, ?, ?, ?
) returning id
`

type CreateImageParams struct {
	Title  string
	Artist string
	Dark   bool
	Data   []byte
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.Title,
		arg.Artist,
		arg.Dark,
		arg.Data,
	)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
delete from images
where id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const getImage = `-- name: GetImage :one
select id, title, artist, dark, data from images
where id = ? limit 1
`

func (q *Queries) GetImage(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Dark,
		&i.Data,
	)
	return i, err
}

const getImageInfo = `-- name: GetImageInfo :one
select id, title, artist from images
where id = ? limit 1
`

type GetImageInfoRow struct {
	ID     int64
	Title  string
	Artist string
}

func (q *Queries) GetImageInfo(ctx context.Context, id int64) (GetImageInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getImageInfo, id)
	var i GetImageInfoRow
	err := row.Scan(&i.ID, &i.Title, &i.Artist)
	return i, err
}

const getRandomImage = `-- name: GetRandomImage :one
select id, title, artist, dark, data from images
order by random() limit 1
`

func (q *Queries) GetRandomImage(ctx context.Context) (Image, error) {
	row := q.db.QueryRowContext(ctx, getRandomImage)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Artist,
		&i.Dark,
		&i.Data,
	)
	return i, err
}

const listImageInfo = `-- name: ListImageInfo :many
select id, title, artist from images
order by artist
`

type ListImageInfoRow struct {
	ID     int64
	Title  string
	Artist string
}

func (q *Queries) ListImageInfo(ctx context.Context) ([]ListImageInfoRow, error) {
	rows, err := q.db.QueryContext(ctx, listImageInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImageInfoRow
	for rows.Next() {
		var i ListImageInfoRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Artist); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImages = `-- name: ListImages :many
select id, title, artist, dark, data from images
order by artist
`

func (q *Queries) ListImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Dark,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
