// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Image struct {
	ID         int64
	Title      string
	Artist     sql.NullString
	Background int64
	Data       []byte
	Thumbnail  []byte
}
