// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Image struct {
	ID         int64
	Title      string
	Artist     string
	Background int64
	Data       []byte
}
